version: '3.8'

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  nlp-service:
    build: ./nlp-service
    ports:
      - "9001:9001"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - kafka
      - nlp-service

  spark:
    build: ./spark-job
    depends_on:
      - kafka
      - nlp-service